name: File Host Docker Build and Push GHCR

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    tags:
      - release/**

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/release/}" >> $GITHUB_OUTPUT
      -
        name: Build and push web filehost image to GHCR
        uses: docker/bake-action@v6
        with:
            source: .
            push: true
            targets: default
            files: |
                docker-bake.hcl
            set: |
                *.tags=ghcr.io/${{ github.repository_owner }}/filehost:latest
                *.tags=ghcr.io/${{ github.repository_owner }}/filehost:${{ steps.get_version.outputs.VERSION }}